### ISSUE TITLE
sm2 interaction between golang libs

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/GM-interoperability#15]
encrypt/decrypt file.
sign/verify
etc...

**Comment by davidkhala** [comment]
What does the `file` here mean?

**Comment by SamYuan1990** [comment]
> What does the `file` here mean?

I suppose we don't need pass data via file.
just 
```
sm2 key
sm2 key encrypt origin data with tj-gm for sample
sm2 key decrypt with ccs-gm for sample
assert decrypted same with origin data
```

**Comment by davidkhala** [comment]
Each key object in different libs can have different object structure and method. instead of file I would rather say the data exchange media is byte array.

**Comment by davidkhala** [comment]
Finally we get all cases green in CI, cheers!
🍷
